### ISSUE TITLE
runner not opening after closing manually

### ISSUE THREAD

**Issue by ShinyZero0** [jghauser/kitty-runner.nvim#11]
I'm on linux with i3wm and nushell. When i open and close runner with commands everything is ok, but after i close it manually with e.g. pressing <C-d> in shell or by closing the last tab or the wm window it won't open again until i kill the "runner" from nvim

**Comment by lolpie244** [comment]
Hi! I wrote alternative plugin, that fix this bug: https://github.com/lolpie244/simple-kitty-runner.nvim/tree/main

**Comment by jghauser** [comment]
@lolpie244, nice one!

**Comment by lolpie244** [comment]
@jghauser sorry for the offtopic question, but do you know how to pass kitty unix socket via ssh to the server?

**Comment by ShinyZero0** [comment]
@lolpie244 try `socat`, or maybe pipe back what you want through ssh and `tee` to socket or whatever. Or combine them

**Comment by lolpie244** [comment]
Thanks! But I found another solution without external programs (https://github.com/lolpie244/simple-kitty-runner.nvim/tree/ssh#ssh)

**Comment by jghauser** [comment]
This should now work. Let me know if you have any issues and thanks for the report!
