### ISSUE TITLE
Escape sequences being already parsed

### ISSUE THREAD

**Issue by Soliprem** [jghauser/kitty-runner.nvim#15]
![image](https://github.com/jghauser/kitty-runner.nvim/assets/73885403/bfc3677f-2d13-42df-afe1-7b44fedb7dc0)
See image: the expected behavior would be to have the \n be sent normally, while instead the text is being already formatted

**Comment by jghauser** [comment]
I pushed a fix so that (at least the most common) escape sequences are now themselves escaped so that they get sent normally. Let me know if you have any issues and thanks for the report!
