### ISSUE TITLE
Can runner be configured to open a new window/tab instead of an entirely new instance of kitty?

### ISSUE THREAD

**Issue by ddanieltan** [jghauser/kitty-runner.nvim#6]
My intended usage is to open up a REPL in the runner, and open up neovim to edit files in my current kitty window.
I pipe lines from my editor over to the repl, and this works flawlessly for the main REPL environments I use (python, scala).
My only gripe is that 2 separate Kitty instances are created, so I can't use my shortcuts to jump between these 2 terminals without using the mouse. If I could open the runner as a separate tab/window, I could navigate entirely from the keyboard.

**Comment by jghauser** [comment]
Hey @ddanieltan! I would imagine that it wouldn't be hard to support that, though it's not currently implemented. I personally use sway as my window manager and use that for my tiling and tabbing needs. I therefore never use kitty's tabs/windows.

I'm currently quite busy, so I'm not sure when I'll get to take a look at this, but if you feel like writing a PR, then I'd be more than happy to merge that! :)

**Comment by ddanieltan** [comment]
Thanks for the quick reply @jghauser. I have never taken a look into the internals of a neovim plugins but this seems like as good a reason as any to give it a go. Will try my hand at a PR.

**Comment by jghauser** [comment]
Great to hear that! If you'd like any pointers, let me know :)

**Comment by ejuarezg** [comment]
This functionality would be awesome :)

**Comment by jghauser** [comment]
Hey, I've merged #10 (thanks @LkeMitchll!), which should implement the functionality asked for here. If not, please get back, and I'll re-open the issue!
